///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Add_multiple_entries recording.
    /// </summary>
    [TestModule("35e06a5c-5eb6-47b0-a83f-926e27528162", ModuleType.Recording, 1)]
    public partial class Add_multiple_entries : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TCOS_POC_DEMOAPPRepository repository.
        /// </summary>
        public static TCOS_POC_DEMOAPPRepository repo = TCOS_POC_DEMOAPPRepository.Instance;

        static Add_multiple_entries instance = new Add_multiple_entries();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Add_multiple_entries()
        {
            firstname = "JOHN";
            lastname = "SMITH";
            age = "45";
            entryValue = "SNEHA RAJ (female, 22) Sales";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Add_multiple_entries Instance
        {
            get { return instance; }
        }

#region Variables

        string _firstname;

        /// <summary>
        /// Gets or sets the value of variable firstname.
        /// </summary>
        [TestVariable("c97e348b-7d61-492f-b8b0-9eeb42b8f36a")]
        public string firstname
        {
            get { return _firstname; }
            set { _firstname = value; }
        }

        string _lastname;

        /// <summary>
        /// Gets or sets the value of variable lastname.
        /// </summary>
        [TestVariable("98b683dd-753b-4e21-a188-14dd32ae61a6")]
        public string lastname
        {
            get { return _lastname; }
            set { _lastname = value; }
        }

        string _age;

        /// <summary>
        /// Gets or sets the value of variable age.
        /// </summary>
        [TestVariable("bb352ca0-79e5-4856-bcc1-a359d6187b2a")]
        public string age
        {
            get { return _age; }
            set { _age = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Department.
        /// </summary>
        [TestVariable("c54e8383-7394-48be-8776-de287dc7a487")]
        public string Department
        {
            get { return repo.Department; }
            set { repo.Department = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable genderRef.
        /// </summary>
        [TestVariable("3f57fc58-0ea7-46c3-b44c-a6aa0d3a2fd0")]
        public string genderRef
        {
            get { return repo.genderRef; }
            set { repo.genderRef = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable entryValue.
        /// </summary>
        [TestVariable("4e81c6b9-a94a-46fa-b759-7c1ee8400315")]
        public string entryValue
        {
            get { return repo.entryValue; }
            set { repo.entryValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.FirstName' at 124;11.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard.FirstName.Click("124;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.FirstName' at 142;13.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.FirstName.Click("142;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$firstname' with focus on 'RxMainFrame.RxTabStandard.FirstName'.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard.FirstName.PressKeys(firstname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.LastName' at 19;11.", repo.RxMainFrame.RxTabStandard.LastNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard.LastName.Click("19;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$lastname' with focus on 'RxMainFrame.RxTabStandard.LastName'.", repo.RxMainFrame.RxTabStandard.LastNameInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RxTabStandard.LastName.PressKeys(lastname);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Open' at 3;7.", repo.RxMainFrame.RxTabStandard.OpenInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard.Open.Click("3;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Department' at 209;1.", repo.List1000.DepartmentInfo, new RecordItemIndex(6));
            repo.List1000.Department.Click("209;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.UpDownEdit' at 36;11.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.Click("36;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$age' with focus on 'RxMainFrame.RxTabStandard.UpDownEdit'.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.PressKeys(age);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Gender' at 9;9.", repo.RxMainFrame.RxTabStandard.GenderInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabStandard.Gender.Click("9;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.BtnAddPerson' at 34;12.", repo.RxMainFrame.RxTabStandard.BtnAddPersonInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabStandard.BtnAddPerson.Click("34;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.RxTabStandard.EntryValue'.", repo.RxMainFrame.RxTabStandard.EntryValueInfo, new RecordItemIndex(11));
            Validate.Exists(repo.RxMainFrame.RxTabStandard.EntryValueInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
