///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Compare_Listbox_Values recording.
    /// </summary>
    [TestModule("33a820f1-3795-435b-a154-98d6a73a83cf", ModuleType.Recording, 1)]
    public partial class Compare_Listbox_Values : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TCOS_POC_DEMOAPPRepository repository.
        /// </summary>
        public static TCOS_POC_DEMOAPPRepository repo = TCOS_POC_DEMOAPPRepository.Instance;

        static Compare_Listbox_Values instance = new Compare_Listbox_Values();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Compare_Listbox_Values()
        {
            listvalue = "";
            listItems = "";
            subTreeItems = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Compare_Listbox_Values Instance
        {
            get { return instance; }
        }

#region Variables

        string _listvalue;

        /// <summary>
        /// Gets or sets the value of variable listvalue.
        /// </summary>
        [TestVariable("2835483b-64e6-415f-bfad-9ffd3d136453")]
        public string listvalue
        {
            get { return _listvalue; }
            set { _listvalue = value; }
        }

        string _listItems;

        /// <summary>
        /// Gets or sets the value of variable listItems.
        /// </summary>
        [TestVariable("58d63425-9043-4a8d-b450-fce2f211239b")]
        public string listItems
        {
            get { return _listItems; }
            set { _listItems = value; }
        }

        string _subTreeItems;

        /// <summary>
        /// Gets or sets the value of variable subTreeItems.
        /// </summary>
        [TestVariable("79f7b6fe-df4c-415f-8a0f-70376e836312")]
        public string subTreeItems
        {
            get { return _subTreeItems; }
            set { _subTreeItems = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 7;9.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabUIElements.Down.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 7;9.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabUIElements.Down.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 7;9.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabUIElements.Down.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 11;14.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabUIElements.Down.Click("11;14");
            Delay.Milliseconds(0);
            
            //Get_value_LstTestBox(repo.RxMainFrame.RxTabUIElements.LstTestBoxInfo, listItems);
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
