///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Expand_Items_In_TreeView recording.
    /// </summary>
    [TestModule("d2875bc7-a379-4831-97e7-14f1684e3797", ModuleType.Recording, 1)]
    public partial class Expand_Items_In_TreeView : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TCOS_POC_DEMOAPPRepository repository.
        /// </summary>
        public static TCOS_POC_DEMOAPPRepository repo = TCOS_POC_DEMOAPPRepository.Instance;

        static Expand_Items_In_TreeView instance = new Expand_Items_In_TreeView();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Expand_Items_In_TreeView()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Expand_Items_In_TreeView Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable parentTreeItem.
        /// </summary>
        [TestVariable("40e00175-060a-4c33-b165-6c1d126d3bf8")]
        public string parentTreeItem
        {
            get { return repo.parentTreeItem; }
            set { repo.parentTreeItem = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;10.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 11;11.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("11;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 9;23.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("9;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Up}{Up}{Up}{Up 2}{Up}{Up}{Up}{Up}{Up}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Up}{Up}{Up}{Up 2}{Up}{Up}{Up}{Up}{Up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;25.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;48.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;48");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 12;45.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("12;45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 12;66.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("12;66");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.MainTreeItem' at 23;4.", repo.RxMainFrame.RxTabUIElements.MainTreeItemInfo, new RecordItemIndex(11));
            repo.RxMainFrame.RxTabUIElements.MainTreeItem.Click("23;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.MainTreeItem'.", repo.RxMainFrame.RxTabUIElements.MainTreeItemInfo, new RecordItemIndex(12));
            repo.RxMainFrame.RxTabUIElements.MainTreeItem.PressKeys("{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 9;66.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(13));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("9;66");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;86.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(14));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;86");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down 7}{Down 2}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(15));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down 7}{Down 2}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Up 16}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(16));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Up 16}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 11;63.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(17));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("11;63");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 13;99.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(18));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("13;99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down 13}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(19));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down 13}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;46.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(20));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;46");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 10;118.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(21));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("10;118");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(22));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 13;78.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(23));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("13;78");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
