///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Remove_multiple_entries recording.
    /// </summary>
    [TestModule("0a29d09b-e646-43e0-8e2b-1c717413faf1", ModuleType.Recording, 1)]
    public partial class Remove_multiple_entries : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TCOS_POC_DEMOAPPRepository repository.
        /// </summary>
        public static TCOS_POC_DEMOAPPRepository repo = TCOS_POC_DEMOAPPRepository.Instance;

        static Remove_multiple_entries instance = new Remove_multiple_entries();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Remove_multiple_entries()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Remove_multiple_entries Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable entryValue.
        /// </summary>
        [TestVariable("07d1cd85-c77c-4374-bae7-acfe27b4eb7a")]
        public string entryValue
        {
            get { return repo.entryValue; }
            set { repo.entryValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.EntryValue' at 155;12.", repo.RxMainFrame.RxTabStandard.EntryValueInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard.EntryValue.Click("155;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.BtnDeletePerson' at 16;10.", repo.RxMainFrame.RxTabStandard.BtnDeletePersonInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.BtnDeletePerson.Click("16;10");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'RxMainFrame.RxTabStandard.EntryValue'.", repo.RxMainFrame.RxTabStandard.EntryValueInfo, new RecordItemIndex(2));
            //Validate.NotExists(repo.RxMainFrame.RxTabStandard.EntryValueInfo);
            //Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
