///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Select_All_Table_Rows recording.
    /// </summary>
    [TestModule("8a48b0be-7d86-4770-a456-b3bd4ab52113", ModuleType.Recording, 1)]
    public partial class Select_All_Table_Rows : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TCOS_POC_DEMOAPPRepository repository.
        /// </summary>
        public static TCOS_POC_DEMOAPPRepository repo = TCOS_POC_DEMOAPPRepository.Instance;

        static Select_All_Table_Rows instance = new Select_All_Table_Rows();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Select_All_Table_Rows()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Select_All_Table_Rows Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.FirstNameRow0' at 32;10.", repo.RxMainFrame.DataGridView1.FirstNameRow0Info, new RecordItemIndex(0));
            repo.RxMainFrame.DataGridView1.FirstNameRow0.Click("32;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.DataGridView1.FirstNameRow0'.", repo.RxMainFrame.DataGridView1.FirstNameRow0Info, new RecordItemIndex(1));
            repo.RxMainFrame.DataGridView1.FirstNameRow0.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.IORow7' at 11;5.", repo.RxMainFrame.DataGridView1.IORow7Info, new RecordItemIndex(2));
            repo.RxMainFrame.DataGridView1.IORow7.Click("11;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.Row7' at 18;8.", repo.RxMainFrame.DataGridView1.Row7Info, new RecordItemIndex(3));
            repo.RxMainFrame.DataGridView1.Row7.Click("18;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.FirstNameRow7' at 47;1.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(4));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.Click("47;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.FirstNameRow7' at 49;2.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(5));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.Click("49;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.FirstNameRow7' at 49;2.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(6));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.Click("49;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}{Back}{Back}{Back}Nicole' with focus on 'RxMainFrame.DataGridView1.FirstNameRow7'.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(7));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.PressKeys("{Back}{Back}{Back}{Back}{Back}{Back}Nicole");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'RxMainFrame.DataGridView1.FirstNameRow7'.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(8));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'RxMainFrame.RxTabUIElements.Position' at 218;11.", repo.RxMainFrame.RxTabUIElements.PositionInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabUIElements.Position.MoveTo("218;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'RxMainFrame.RxTabUIElements.Position' at 236;11.", repo.RxMainFrame.RxTabUIElements.PositionInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabUIElements.Position.MoveTo("236;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
