///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SHOWIMAGE recording.
    /// </summary>
    [TestModule("5fc36536-d961-4508-a4a3-fdc54649a5e1", ModuleType.Recording, 1)]
    public partial class SHOWIMAGE : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TCOS_POC_DEMOAPPRepository repository.
        /// </summary>
        public static TCOS_POC_DEMOAPPRepository repo = TCOS_POC_DEMOAPPRepository.Instance;

        static SHOWIMAGE instance = new SHOWIMAGE();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SHOWIMAGE()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SHOWIMAGE Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased1.ChkShowImage' at 7;9.", repo.RxMainFrame.RxTabImageBased1.ChkShowImageInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabImageBased1.ChkShowImage.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'RxMainFrame.RxTabImageBased1.ChkShowImage'.", repo.RxMainFrame.RxTabImageBased1.ChkShowImageInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabImageBased1.ChkShowImageInfo, "Checked", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.RxTabImageBased1.TheCat'.", repo.RxMainFrame.RxTabImageBased1.TheCatInfo, new RecordItemIndex(2));
            Validate.Exists(repo.RxMainFrame.RxTabImageBased1.TheCatInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased1.ChkShowImage' at 4;5.", repo.RxMainFrame.RxTabImageBased1.ChkShowImageInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabImageBased1.ChkShowImage.Click("4;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'RxMainFrame.RxTabImageBased1.ChkShowImage'.", repo.RxMainFrame.RxTabImageBased1.ChkShowImageInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabImageBased1.ChkShowImageInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
